require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrunchCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # CrunchCompany. As you add validations to CrunchCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "company_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CrunchCompaniesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all crunch_companies as @crunch_companies" do
      crunch_company = CrunchCompany.create! valid_attributes
      get :index, {}, valid_session
      assigns(:crunch_companies).should eq([crunch_company])
    end
  end

  describe "GET show" do
    it "assigns the requested crunch_company as @crunch_company" do
      crunch_company = CrunchCompany.create! valid_attributes
      get :show, {:id => crunch_company.to_param}, valid_session
      assigns(:crunch_company).should eq(crunch_company)
    end
  end

  describe "GET new" do
    it "assigns a new crunch_company as @crunch_company" do
      get :new, {}, valid_session
      assigns(:crunch_company).should be_a_new(CrunchCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested crunch_company as @crunch_company" do
      crunch_company = CrunchCompany.create! valid_attributes
      get :edit, {:id => crunch_company.to_param}, valid_session
      assigns(:crunch_company).should eq(crunch_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CrunchCompany" do
        expect {
          post :create, {:crunch_company => valid_attributes}, valid_session
        }.to change(CrunchCompany, :count).by(1)
      end

      it "assigns a newly created crunch_company as @crunch_company" do
        post :create, {:crunch_company => valid_attributes}, valid_session
        assigns(:crunch_company).should be_a(CrunchCompany)
        assigns(:crunch_company).should be_persisted
      end

      it "redirects to the created crunch_company" do
        post :create, {:crunch_company => valid_attributes}, valid_session
        response.should redirect_to(CrunchCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crunch_company as @crunch_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrunchCompany.any_instance.stub(:save).and_return(false)
        post :create, {:crunch_company => { "company_name" => "invalid value" }}, valid_session
        assigns(:crunch_company).should be_a_new(CrunchCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CrunchCompany.any_instance.stub(:save).and_return(false)
        post :create, {:crunch_company => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crunch_company" do
        crunch_company = CrunchCompany.create! valid_attributes
        # Assuming there are no other crunch_companies in the database, this
        # specifies that the CrunchCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CrunchCompany.any_instance.should_receive(:update_attributes).with({ "company_name" => "MyString" })
        put :update, {:id => crunch_company.to_param, :crunch_company => { "company_name" => "MyString" }}, valid_session
      end

      it "assigns the requested crunch_company as @crunch_company" do
        crunch_company = CrunchCompany.create! valid_attributes
        put :update, {:id => crunch_company.to_param, :crunch_company => valid_attributes}, valid_session
        assigns(:crunch_company).should eq(crunch_company)
      end

      it "redirects to the crunch_company" do
        crunch_company = CrunchCompany.create! valid_attributes
        put :update, {:id => crunch_company.to_param, :crunch_company => valid_attributes}, valid_session
        response.should redirect_to(crunch_company)
      end
    end

    describe "with invalid params" do
      it "assigns the crunch_company as @crunch_company" do
        crunch_company = CrunchCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrunchCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => crunch_company.to_param, :crunch_company => { "company_name" => "invalid value" }}, valid_session
        assigns(:crunch_company).should eq(crunch_company)
      end

      it "re-renders the 'edit' template" do
        crunch_company = CrunchCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CrunchCompany.any_instance.stub(:save).and_return(false)
        put :update, {:id => crunch_company.to_param, :crunch_company => { "company_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crunch_company" do
      crunch_company = CrunchCompany.create! valid_attributes
      expect {
        delete :destroy, {:id => crunch_company.to_param}, valid_session
      }.to change(CrunchCompany, :count).by(-1)
    end

    it "redirects to the crunch_companies list" do
      crunch_company = CrunchCompany.create! valid_attributes
      delete :destroy, {:id => crunch_company.to_param}, valid_session
      response.should redirect_to(crunch_companies_url)
    end
  end

end
